---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.2.4
_src_path: gh:kc-workspace/asdf-plugin-template.git
addon_yaml:
    archive: true
    checksum: true
    download: true
    fetch: true
    git: false
    github: true
    gpg: true
    help: true
    install: true
    package: false
    python: false
    system: true
    tags: true
    version: false
app_desc: Provision, change, and version resources on any environment
app_name: terraform
app_repo: https://github.com/hashicorp/terraform
app_type: standalone
app_website: https://www.hashicorp.com/products/terraform
archive_conf_path: ''
archive_conf_strip: 0
archive_enabled: true
archive_regex: \.zip$
checksum_conf_algorithm: 256
checksum_enabled: true
checksum_url: https://releases.hashicorp.com/terraform/{version}/terraform_{version}_SHA256SUMS
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_require_commands: ''
download_url: https://releases.hashicorp.com/terraform/{version}/terraform_{version}_{os}_{arch}.zip
gpg_enabled: true
gpg_public_key_email: ''
gpg_public_key_fingerprint: C874011F0AB405110D02105534365D9472D7468F
gpg_public_key_keyid: ''
gpg_public_key_link: https://www.hashicorp.com/.well-known/pgp-key.txt
gpg_public_key_type: link
gpg_sig_url: https://releases.hashicorp.com/terraform/{version}/terraform_{version}_SHA256SUMS.sig
install_map_enabled: true
install_map_method: move
install_map_yaml:
    terraform: bin/terraform
package_enabled: false
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-terraform
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-terraform.git
source_enabled: false
sys_arch_enabled: true
sys_arch_yaml:
    aarch64*: arm64
    armv5*: armv5
    armv6*: armv6
    armv7*: armv7
    i386: '386'
    i686: '386'
    powerpc64le: ppc64le
    ppc64le: ppc64le
    x86: '386'
    x86_64: amd64
sys_ext_enabled: false
sys_os_enabled: false
test_cmd_args: --version
version_file_enabled: false
version_prefix: v
